name: drink-a-drink

services:
  app:
    image: ghcr.io/gregpesc/progetto_terranova-app:latest
    hostname: app
    container_name: app
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail localhost:8080/healthcheck || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - database:/deploy-dir/instance
      - uploads:/deploy-dir/app/uploads
    # command: "gunicorn --bind 0.0.0.0:8080 run:app"

  caddy:
    image: ghcr.io/gregpesc/progetto_terranova-caddy:latest
    hostname: caddy
    container_name: caddy
    restart: always
    environment:
      - TZ=Europe/Rome
      - MY_DOMAIN=drinkadrink.me
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
  database:
  uploads:
